// Generated by ReScript, PLEASE EDIT WITH CARE


var axiosConfig = {
  baseURL: "https://opentdb.com"
};

var questionAmount = 10;

var questionType = "multiple";

export {
  axiosConfig ,
  questionAmount ,
  questionType ,
  
}
/* No side effect */
