// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Axios from "axios";
import * as React from "react";
import * as $$Promise from "reason-promise/src/js/promise.mjs";
import * as AppConfig from "./config/AppConfig.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

var $$Window = {};

var initialProps_questions = [];

var initialProps = {
  questions: initialProps_questions,
  currentQuestionIndex: 0
};

function getServerSideProps(_ctx) {
  return $$Promise.Js.map(Axios.get("/api.php?amount=" + String(AppConfig.questionAmount) + "&type=" + AppConfig.questionType, AppConfig.axiosConfig), (function (param) {
                return {
                        props: {
                          questions: param.data.results,
                          currentQuestionIndex: 0
                        }
                      };
              }));
}

function randomizeAnswers(question) {
  return Belt_Array.shuffle(Belt_Array.concat([question.correct_answer], question.incorrect_answers));
}

function handleSubmit($$event, question) {
  $$event.preventDefault();
  var selectedAnswer = $$event.target.answer.value;
  if (selectedAnswer === question.correct_answer) {
    window.alert("Correct answer");
  } else {
    window.alert("The correct answer is " + question.correct_answer);
  }
  
}

function $$default(param) {
  var currentQuestionIndex = param.currentQuestionIndex;
  var questions = param.questions;
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "text-3xl font-semibold",
                  dangerouslySetInnerHTML: {
                    __html: Caml_array.get(questions, currentQuestionIndex).question
                  }
                }), React.createElement("form", {
                  onSubmit: (function ($$event) {
                      return handleSubmit($$event, Caml_array.get(questions, currentQuestionIndex));
                    })
                }, React.createElement("ol", {
                      type: "a"
                    }, Belt_Array.mapWithIndex(randomizeAnswers(Caml_array.get(questions, currentQuestionIndex)), (function (index, answer) {
                            return React.createElement("li", {
                                        key: answer,
                                        className: "my-2"
                                      }, React.createElement("input", {
                                            className: "mr-2",
                                            id: "answer" + String(index),
                                            name: "answer",
                                            type: "radio",
                                            value: answer
                                          }), React.createElement("label", undefined, answer));
                          }))), React.createElement("button", {
                      className: "mt-4 bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded",
                      type: "submit"
                    }, "Submit answer")));
}

export {
  $$Window ,
  initialProps ,
  getServerSideProps ,
  randomizeAnswers ,
  handleSubmit ,
  $$default ,
  $$default as default,
  
}
/* axios Not a pure module */
